### numpy array 연산
for문 사용할 필요없이 array 자체 연산 가능

In [1]:
import numpy as np

In [2]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [3]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [10]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array1 = array1 * 2

In [14]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [16]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [17]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [18]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

### 실습

In [21]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

won_array = np.array(revenue_in_yen) * 10.08

won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

In [22]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]


won_array = np.array(revenue_in_yen) * 10.08 + np.array(revenue_in_dollar) * 1138

won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

### Boolean 연산

In [23]:
import numpy as np

In [24]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [25]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [26]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [27]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])

In [28]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10]),)

In [30]:
filter = np.where(array1 > 4) 
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

In [31]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

### 실습

In [34]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_yen_np_array = np.array(revenue_in_yen)
filter = np.where(revenue_in_yen_np_array <= 200000)
bad_days_revenue = revenue_in_yen_np_array[filter]
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

### 통계
max, min : 최대, 최소  
mean : 평균  
median : 중앙값  
std : 표준 편차
var : 분산

In [35]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

In [36]:
array1.max()

31

In [37]:
array1.min()

5

In [38]:
array1.mean()

15.25

In [39]:
np.median(array1)

13.5

In [40]:
array1.std()

8.496322733983215

In [42]:
array1.var()

72.1875